runtime: python39

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto

env_variables:
  PORT: 8080

